# the annotation export option.
#
# root<string>: the annotation exporter running directory.
#
# output<string>: the directory where the annotation exporter generated code saved.
#
# replaces<map[string][]string>: the import path alias. 
# Some package's name is different from its folder name, may need alias to make sure 
# the annotation exporter be able to found the correct import path.
#
# example: 
#
# root: .
# output: ./annotation
# replace: 
#   - github.com/example/example/v1: 
#       - example1
#       - example2

root: testdata
output: testdata/annotation
replaces: {}
