// Code generated by godoc. DO NOT EDIT.
// 代码由godoc自动生成，请勿修改！
// version: v0.0.1

package godoc

import(
    "gitlab.isigning.cn/laixinchen/documents/elements"

    "example/exapmle"
)

var nodes = map[string]*elements.Node{
    "example/exapmle.Request": {
		Type: elements.TypeStruct,
		Name: "Request",
		Ptr: new(exapmle.Request),
		Path: "example/exapmle.Request",
		Comments: []string{"Request", "@summary request example"},
		Annotations: []*elements.Annotation{
            {
				Raw: "@summary request example",
				Content: "summary request example",
				Relation: []interface{}{},
			},
		},
	},
    "example/exapmle.Handle": {
		Type: elements.TypeFunc,
		Name: "Handle",
		Ptr: exapmle.Handle,
		Path: "example/exapmle.Handle",
		Comments: []string{"Handle", "hahahaha", "@header content-type:application/json", "@request [Request]", "@response [Response]"},
		Annotations: []*elements.Annotation{
            {
				Raw: "@header content-type:application/json",
				Content: "header content-type:application/json",
				Relation: []interface{}{},
			},
            {
				Raw: "@request [Request]",
				Content: "request [example/exapmle.Request]",
				Relation: []interface{}{new(exapmle.Request), },
			},
            {
				Raw: "@response [Response]",
				Content: "response [example/exapmle.Response]",
				Relation: []interface{}{new(exapmle.Response), },
			},
		},
	},
}

func Nodes() map[string]*elements.Node {
	return nodes
}

